### ISSUE TITLE
Does not work when pop/pushState is used

### ISSUE THREAD

**Issue by whitneyit** [mikaelbr/chrome-github-packages#5]

**Comment by darsain** [comment]
Is this fixed and published? Because the extension isn't kicking in when I just navigate a file tree. I have to F5 when looking at `package.json`.

**Comment by mikaelbr** [comment]
This should be published in version 4. Maybe Github has made some changes.

**Comment by whitneyit** [comment]
I think something has changed again. If I disable the plugin and just copy
and paste the source into the console it seems to
work. I'll try tinkering with it some more

**Comment by mikaelbr** [comment]
@whitneyit I made you collaborator so you can push code directly if you want :)

**Comment by whitneyit** [comment]
Awesome cheers. I'll have another look tonight

**Comment by whitneyit** [comment]
@mikaelbr Ready for release

**Comment by mikaelbr** [comment]
Good job! I'll release it as soon as I can.

**Comment by mikaelbr** [comment]
Published now

**Comment by whitneyit** [comment]
Awesome
